.github/pull_request_template.md
CHANGES.txt
splitio/engine/engine.go
splitio/engine/engine_test.go
splitio/version.go

* [SDKS-344](https://splitio.atlassian.net/browse/SDKS-344)
* Updated Engine.
* Added unit tests.
* Run `go test ./...`

[GO]: Traffic Allocation 1 bucket off fix

---

splitio/client/client.go
splitio/client/client_test.go
splitio/client/factory.go
splitio/client/input_validator.go
splitio/client/input_validator_test.go
splitio/client/manager.go
splitio/conf/sdkconf.go
splitio/engine/grammar/matchers/partofset.go
splitio/service/api/client.go
splitio/service/api/http_fetchers.go
splitio/service/api/http_recorders.go

* [SDKS-411](https://splitio.atlassian.net/browse/SDKS-411)
* Updated Input Validation for `Treatment`, `Track` and `Manager`.
* Added validation on `Destroy()`
* Added validation on `Treatments` call.

[SDKS-411]: Go Input validation

---

CHANGES.txt
splitio/conf/defaults.go
splitio/conf/sdkconf.go
splitio/version.go

* [SDKS-486]: Update featuresRefreshRate to be 5 seconds 
* Bullet 1
* Bullet 2
* Bullet 1
* Bullet 2

[SDKS-486]: Update featuresRefreshRate to be 5 seconds 

---

splitio/engine/engine_test.go

* [SDKS-{TICKET}](https://splitio.atlassian.net/browse/SDKS-{TICKET})
* Bullet 1
* Bullet 2
* Bullet 1
* Bullet 2

added consistency treatments test

---

CHANGES.txt
splitio/client/client.go
splitio/client/client_test.go
splitio/client/factory.go
splitio/client/input_validator_test.go
splitio/client/manager.go
splitio/client/manager_test.go
splitio/conf/defaults.go
splitio/conf/sdkconf.go
splitio/version.go

* [SDKS-496](https://splitio.atlassian.net/browse/SDKS-496)
* Updated BUR

[SDKS-496]: BUR refactor

---

splitio/client/client.go
splitio/client/client_test.go
splitio/client/input_validator.go
splitio/client/input_validator_test.go
splitio/engine/evaluator/evaluator.go

* [SDKS-613: Add treatmentWithConfig method](https://splitio.atlassian.net/browse/SDKS-613)
* Added TreatmentWithConfig method.
* Moved doTreatmentCall to be reused for Treatment and TreatmentWithConfig

[SDKS-613]: Add treatmentWithConfig method

---

splitio/client/client.go
splitio/client/client_test.go
splitio/client/input_validator.go
splitio/version.go

* [SDKS-614: Add treatmentsWithConfig method](https://splitio.atlassian.net/browse/SDKS-614)
* Added `TreatmentsWithConfig` method.

[SDKS-614]: Add treatmentsWithConfig method

---

splitio/client/client_test.go
splitio/client/manager.go
splitio/client/manager_test.go

* [SDKS-615:  Update SplitView for manager to return dynamic configs](https://splitio.atlassian.net/browse/SDKS-615)
* Updated `SplitView` to have `Configs` variable.
* Updated tests for `Manager`

[SDKS-615]:  Update SplitView for manager to return dynamic configs

---

splitio/client/client_test.go
splitio/client/factory.go
splitio/service/local/splitFetcher.go
splitio/version.go
testdata/splits.yaml

* [SDKS-654: Update localhost mode to use yaml with configs](https://splitio.atlassian.net/browse/SDKS-654)
* Added support for YAML for localhost mode.
* Added tests

[SDKS-654]: Update localhost mode to use yaml with configs

---

CHANGES.txt
splitio/client/client.go
splitio/client/client_test.go
splitio/client/manager.go
splitio/engine/evaluator/evaluator.go
splitio/engine/evaluator/impressionlabels/impression_labels.go
splitio/version.go

* [SDKS-686](https://splitio.atlassian.net/browse/SDKS-686)
* Added not ready label.
* Updated impression to be stored with that label.
* Updated tests.

[SDKS-686]: Add SDK_NOT_READY label

---

.github/pull_request_template.md
CHANGES.txt
CONTRIBUTORS-GUIDE.md
Detailed-README.md
README.md
TODO.txt

* Added `CONTRIBUTORS-GUIDE`.
* Updated Readme.md and `pull_request_template`

Documentation revamp

---

README.md

This PR fixes the issue tracker link in the readme.
Click the issue tracker link to check that it opens https://github.com/splitio/go-client/issues.

Fix issue tracker readme link

---

CHANGES.txt
splitio/client/client.go
splitio/client/client_test.go
splitio/client/factory.go
splitio/client/factory_tracker_test.go
splitio/client/input_validator_test.go
splitio/conf/sdkconf.go
splitio/conf/sdkconf_test.go
splitio/version.go

added modes with const

---

CHANGES.txt
Gopkg.toml
splitio/client/client.go
splitio/client/client_test.go
splitio/client/factory.go
splitio/client/factory_tracker.go
splitio/client/input_validator_test.go
splitio/client/manager.go
splitio/client/manager_test.go
splitio/conf/defaults.go
splitio/conf/sdkconf.go
splitio/conf/sdkconf_test.go
splitio/conf/util.go
splitio/engine/grammar/matchers/dependency_test/dependency_test.go
splitio/engine/grammar/matchers/insegment_test.go
splitio/version.go

- Added new telemetry.
- Created endpoints for `init` and `stats` telemetry.
- Updated storages.

Integration 5.4.0

---

.github/workflows/ci.yml

AUT-1151 fixes

---

.github/workflows/ci.yml
CHANGES.txt
README.md
splitio/client/client_test.go
splitio/client/factory.go
splitio/version.go

fixed sdk version

---

CHANGES.txt
splitio/conf/sdkconf.go
splitio/engine/grammar/matchers/boolean.go
splitio/version.go

demoted booleanmatcher logging to warning

---

splitio/client/factory.go

- Now we are able to config the impressions period task in Redis.

Configurable period

---

CHANGES.txt
splitio/engine/grammar/matchers/allofset.go
splitio/engine/grammar/matchers/anyofset.go
splitio/engine/grammar/matchers/between.go
splitio/engine/grammar/matchers/contains.go
splitio/engine/grammar/matchers/endswith.go
splitio/engine/grammar/matchers/equalto.go
splitio/engine/grammar/matchers/equaltoset.go
splitio/engine/grammar/matchers/gtoet.go
splitio/engine/grammar/matchers/ltoet.go
splitio/engine/grammar/matchers/partofset.go
splitio/engine/grammar/matchers/regex.go
splitio/engine/grammar/matchers/startswith.go
splitio/engine/grammar/matchers/whitelist.go
splitio/version.go

Replace error messages with warnings.

[SDKS-6232]

---

splitio/conf/sdkconf.go

Added the new segmentDirectory config

[SDKS-6446] Add segmentDirectory config for json localhost

---

splitio/conf/sdkconf.go

Added the new localhostRefreshEnabled config in sdkconf.

[SDKS-6544] Add new config localhostRefreshEnabled

---

go.mod
go.sum
splitio/client/factory.go
splitio/client/input_validator_test.go

Updated factory.go to use  NewFileSegmentFetcher and new config.

[SDKS-6443] Update factory to use segmentFetcher

---

splitio/client/factory.go

Add segment storage to factory.

[SDKS-6449] Add segment storage to factory

---

splitio/client/factory.go

Removed method initializationLocalhost and now use initializationInMemory for localhost.

[SDKS-6573] Update localhost factory

---

CHANGES.txt
go.mod
go.sum
splitio/client/client_test.go
splitio/version.go

- Update common dependency and fix test

Update common dependency

---

splitio/client/input_validator.go
splitio/client/input_validator_test.go

[SDKS-6925] Update input_validator

---

splitio/engine/evaluator/evaluator.go

[SDKS-6926] Update evaluator logs

---

README.md

[SDKS-6953] Update readme

---

splitio/client/factory_tracker.go
splitio/client/factory_tracker_test.go

[SDKS-6954] Update factory_tracker

---

splitio/client/input_validator_test.go
splitio/client/manager.go
splitio/conf/sdkconf.go

[SDKS-6955] Update manager and sdkconf logs

---

splitio/engine/engine.go
splitio/engine/evaluator/interface.go
splitio/engine/grammar/constants.go
splitio/engine/grammar/matchers/allofset.go
splitio/engine/grammar/matchers/anyofset.go
splitio/engine/grammar/matchers/contains.go
splitio/engine/grammar/matchers/dependency.go
splitio/engine/grammar/matchers/endswith.go
splitio/engine/grammar/matchers/equaltoset.go
splitio/engine/grammar/matchers/partofset.go
splitio/engine/grammar/matchers/regex.go
splitio/engine/grammar/matchers/startswith.go
splitio/engine/grammar/split.go

[SDKS-6959] Update feature to feature flag in interface and update split to feature flag in some comments

---

CHANGES.txt
README.md

Update changelog and readme

---

splitio/client/client.go
splitio/client/input_validator_test.go

[SDKS-7625] Add feature flag name in ready warning log

---

go.mod
go.sum
splitio/client/factory.go

Set FlagSetsTotal and FlagSetsInvalid to 0 when consumer mode

---

CHANGES.txt
go.mod
go.sum
splitio/client/client.go
splitio/version.go

[SDKS-7828] Update treatmentsByFlagSets for telemetry

---

go.mod
go.sum
splitio/client/client_test.go
splitio/version.go
testdata/splits_mock_3.json

Add test cases for semver and unsupported matcher
